
# After cloning repo, install hooks with:
#
#     $ brew install pre-commit
#
#     $ pre-commit install

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=100']
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: file-contents-sorter
  - id: mixed-line-ending
  - id: name-tests-test
  - id: trailing-whitespace
