name: mapping

channels:
  - conda-forge

dependencies:
  - flake8 >= 3.8.4
  - isort >= 5.7.0
  - pandas >= 1.2.0
  - pip >= 20.3.3
  - python >= 3.9.1
  - ruamel.yaml >= 0.16.12
  - sqlalchemy >= 1.3.21
  - pip:
#     - sqlalchemy >= 1.4.0b1  # uszipcode is not yet ready for the new sqlalchemy
      - uszipcode >= 0.2.4
